version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=Lab2018*
            - MYSQL_DATABASE=finaldb
        volumes:
            - /home/kelly/trabajo-final-despliegue:/var/lib/mysql
    web:
        build: .
        command: python proyecto-django-jenkins/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

